import type { Metadata } from "next";
import localFont from "next/font/local";
import "xp.css/dist/XP.css";
import "./globals.css";

import { Taskbar } from "@/components/Taskbar";

const tahoma = localFont({
	src: "./fonts/Tahoma.woff",
	variable: "--font-tahoma",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="overflow-hidden">
			<body
				className={`${tahoma.variable} antialiased flex flex-col h-screen w-screen`}
			>
				<main className="w-full h-full max-w-full max-h-full relative bg-[url('/wallpaper.webp')] bg-cover">
					{children}
				</main>
				<Taskbar />
			</body>
		</html>
	);
}
